#
# -Djava.util.logging.config.file=src/main/java/TSiPVSEVM/upr2/rfc2229/logging.properties

.level=ALL
.handlers=java.util.logging.ConsoleHandler, java.util.logging.FileHandler
java.util.logging.FileHandler.pattern = src/main/java/TSiPVSEVM/upr2/rfc2229/server_log.txt
java.util.logging.FileHandler.limit = 1000000
java.util.logging.FileHandler.count = 3
java.util.logging.FileHandler.formatter = java.util.logging.SimpleFormatter


java.util.logging.ConsoleHandler.level=ALL